// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/v1/fleet.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FleetService_Register_FullMethodName      = "/sentinel.v1.FleetService/Register"
	FleetService_ListDevices_FullMethodName   = "/sentinel.v1.FleetService/ListDevices"
	FleetService_DeviceStatus_FullMethodName  = "/sentinel.v1.FleetService/DeviceStatus"
	FleetService_Health_FullMethodName        = "/sentinel.v1.FleetService/Health"
	FleetService_AcceptPairing_FullMethodName = "/sentinel.v1.FleetService/AcceptPairing"
)

// FleetServiceClient is the client API for FleetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FleetService handles device management and health monitoring.
type FleetServiceClient interface {
	// Register a device with the fleet controller.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// List all known devices in the fleet.
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	// Get detailed status for a specific device.
	DeviceStatus(ctx context.Context, in *DeviceStatusRequest, opts ...grpc.CallOption) (*DeviceStatusResponse, error)
	// Health check for the local device.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Accept or process a pairing request.
	AcceptPairing(ctx context.Context, in *PairingRequest, opts ...grpc.CallOption) (*PairingResponse, error)
}

type fleetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFleetServiceClient(cc grpc.ClientConnInterface) FleetServiceClient {
	return &fleetServiceClient{cc}
}

func (c *fleetServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, FleetService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, FleetService_ListDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) DeviceStatus(ctx context.Context, in *DeviceStatusRequest, opts ...grpc.CallOption) (*DeviceStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceStatusResponse)
	err := c.cc.Invoke(ctx, FleetService_DeviceStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, FleetService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) AcceptPairing(ctx context.Context, in *PairingRequest, opts ...grpc.CallOption) (*PairingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PairingResponse)
	err := c.cc.Invoke(ctx, FleetService_AcceptPairing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FleetServiceServer is the server API for FleetService service.
// All implementations must embed UnimplementedFleetServiceServer
// for forward compatibility.
//
// FleetService handles device management and health monitoring.
type FleetServiceServer interface {
	// Register a device with the fleet controller.
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// List all known devices in the fleet.
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	// Get detailed status for a specific device.
	DeviceStatus(context.Context, *DeviceStatusRequest) (*DeviceStatusResponse, error)
	// Health check for the local device.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Accept or process a pairing request.
	AcceptPairing(context.Context, *PairingRequest) (*PairingResponse, error)
	mustEmbedUnimplementedFleetServiceServer()
}

// UnimplementedFleetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFleetServiceServer struct{}

func (UnimplementedFleetServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedFleetServiceServer) ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedFleetServiceServer) DeviceStatus(context.Context, *DeviceStatusRequest) (*DeviceStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeviceStatus not implemented")
}
func (UnimplementedFleetServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedFleetServiceServer) AcceptPairing(context.Context, *PairingRequest) (*PairingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptPairing not implemented")
}
func (UnimplementedFleetServiceServer) mustEmbedUnimplementedFleetServiceServer() {}
func (UnimplementedFleetServiceServer) testEmbeddedByValue()                      {}

// UnsafeFleetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FleetServiceServer will
// result in compilation errors.
type UnsafeFleetServiceServer interface {
	mustEmbedUnimplementedFleetServiceServer()
}

func RegisterFleetServiceServer(s grpc.ServiceRegistrar, srv FleetServiceServer) {
	// If the following call panics, it indicates UnimplementedFleetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FleetService_ServiceDesc, srv)
}

func _FleetService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_DeviceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).DeviceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_DeviceStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).DeviceStatus(ctx, req.(*DeviceStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_AcceptPairing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PairingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).AcceptPairing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_AcceptPairing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).AcceptPairing(ctx, req.(*PairingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FleetService_ServiceDesc is the grpc.ServiceDesc for FleetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FleetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sentinel.v1.FleetService",
	HandlerType: (*FleetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _FleetService_Register_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _FleetService_ListDevices_Handler,
		},
		{
			MethodName: "DeviceStatus",
			Handler:    _FleetService_DeviceStatus_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _FleetService_Health_Handler,
		},
		{
			MethodName: "AcceptPairing",
			Handler:    _FleetService_AcceptPairing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/fleet.proto",
}

const (
	CaptureService_Screenshot_FullMethodName    = "/sentinel.v1.CaptureService/Screenshot"
	CaptureService_CaptureWindow_FullMethodName = "/sentinel.v1.CaptureService/CaptureWindow"
	CaptureService_ListDisplays_FullMethodName  = "/sentinel.v1.CaptureService/ListDisplays"
)

// CaptureServiceClient is the client API for CaptureService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CaptureService handles screen capture operations.
type CaptureServiceClient interface {
	// Capture a screenshot of a display.
	Screenshot(ctx context.Context, in *ScreenshotRequest, opts ...grpc.CallOption) (*ScreenshotResponse, error)
	// Capture a specific window by title.
	CaptureWindow(ctx context.Context, in *CaptureWindowRequest, opts ...grpc.CallOption) (*CaptureWindowResponse, error)
	// List available displays/monitors.
	ListDisplays(ctx context.Context, in *ListDisplaysRequest, opts ...grpc.CallOption) (*ListDisplaysResponse, error)
}

type captureServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCaptureServiceClient(cc grpc.ClientConnInterface) CaptureServiceClient {
	return &captureServiceClient{cc}
}

func (c *captureServiceClient) Screenshot(ctx context.Context, in *ScreenshotRequest, opts ...grpc.CallOption) (*ScreenshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScreenshotResponse)
	err := c.cc.Invoke(ctx, CaptureService_Screenshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureServiceClient) CaptureWindow(ctx context.Context, in *CaptureWindowRequest, opts ...grpc.CallOption) (*CaptureWindowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptureWindowResponse)
	err := c.cc.Invoke(ctx, CaptureService_CaptureWindow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureServiceClient) ListDisplays(ctx context.Context, in *ListDisplaysRequest, opts ...grpc.CallOption) (*ListDisplaysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDisplaysResponse)
	err := c.cc.Invoke(ctx, CaptureService_ListDisplays_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CaptureServiceServer is the server API for CaptureService service.
// All implementations must embed UnimplementedCaptureServiceServer
// for forward compatibility.
//
// CaptureService handles screen capture operations.
type CaptureServiceServer interface {
	// Capture a screenshot of a display.
	Screenshot(context.Context, *ScreenshotRequest) (*ScreenshotResponse, error)
	// Capture a specific window by title.
	CaptureWindow(context.Context, *CaptureWindowRequest) (*CaptureWindowResponse, error)
	// List available displays/monitors.
	ListDisplays(context.Context, *ListDisplaysRequest) (*ListDisplaysResponse, error)
	mustEmbedUnimplementedCaptureServiceServer()
}

// UnimplementedCaptureServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCaptureServiceServer struct{}

func (UnimplementedCaptureServiceServer) Screenshot(context.Context, *ScreenshotRequest) (*ScreenshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Screenshot not implemented")
}
func (UnimplementedCaptureServiceServer) CaptureWindow(context.Context, *CaptureWindowRequest) (*CaptureWindowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CaptureWindow not implemented")
}
func (UnimplementedCaptureServiceServer) ListDisplays(context.Context, *ListDisplaysRequest) (*ListDisplaysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDisplays not implemented")
}
func (UnimplementedCaptureServiceServer) mustEmbedUnimplementedCaptureServiceServer() {}
func (UnimplementedCaptureServiceServer) testEmbeddedByValue()                        {}

// UnsafeCaptureServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CaptureServiceServer will
// result in compilation errors.
type UnsafeCaptureServiceServer interface {
	mustEmbedUnimplementedCaptureServiceServer()
}

func RegisterCaptureServiceServer(s grpc.ServiceRegistrar, srv CaptureServiceServer) {
	// If the following call panics, it indicates UnimplementedCaptureServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CaptureService_ServiceDesc, srv)
}

func _CaptureService_Screenshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScreenshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureServiceServer).Screenshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureService_Screenshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureServiceServer).Screenshot(ctx, req.(*ScreenshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureService_CaptureWindow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureWindowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureServiceServer).CaptureWindow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureService_CaptureWindow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureServiceServer).CaptureWindow(ctx, req.(*CaptureWindowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureService_ListDisplays_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDisplaysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureServiceServer).ListDisplays(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureService_ListDisplays_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureServiceServer).ListDisplays(ctx, req.(*ListDisplaysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CaptureService_ServiceDesc is the grpc.ServiceDesc for CaptureService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CaptureService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sentinel.v1.CaptureService",
	HandlerType: (*CaptureServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Screenshot",
			Handler:    _CaptureService_Screenshot_Handler,
		},
		{
			MethodName: "CaptureWindow",
			Handler:    _CaptureService_CaptureWindow_Handler,
		},
		{
			MethodName: "ListDisplays",
			Handler:    _CaptureService_ListDisplays_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/fleet.proto",
}
