// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/v1/fleet.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	Certificate   []byte                 `protobuf:"bytes,5,opt,name=certificate,proto3" json:"certificate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_v1_fleet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_fleet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_fleet_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RegisterRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *RegisterRequest) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

type RegisterResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Accepted           bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ControllerDeviceId string                 `protobuf:"bytes,2,opt,name=controller_device_id,json=controllerDeviceId,proto3" json:"controller_device_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_v1_fleet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_fleet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_fleet_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterResponse) GetControllerDeviceId() string {
	if x != nil {
		return x.ControllerDeviceId
	}
	return ""
}

type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_proto_v1_fleet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_fleet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_fleet_proto_rawDescGZIP(), []int{2}
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DeviceInfo          `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_proto_v1_fleet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_fleet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_fleet_proto_rawDescGZIP(), []int{3}
}

func (x *ListDevicesResponse) GetDevices() []*DeviceInfo {
	if x != nil {
		return x.Devices
	}
	return nil
}

type DeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	LastSeenUnix  int64                  `protobuf:"varint,7,opt,name=last_seen_unix,json=lastSeenUnix,proto3" json:"last_seen_unix,omitempty"`
	Address       string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_proto_v1_fleet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_fleet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_proto_v1_fleet_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceInfo) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *DeviceInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *DeviceInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *DeviceInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *DeviceInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeviceInfo) GetLastSeenUnix() int64 {
	if x != nil {
		return x.LastSeenUnix
	}
	return 0
}

func (x *DeviceInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type DeviceStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceStatusRequest) Reset() {
	*x = DeviceStatusRequest{}
	mi := &file_proto_v1_fleet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStatusRequest) ProtoMessage() {}

func (x *DeviceStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_fleet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStatusRequest.ProtoReflect.Descriptor instead.
func (*DeviceStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_fleet_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceStatusRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type DeviceStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *DeviceInfo            `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryPercent float64                `protobuf:"fixed64,3,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	DiskPercent   float64                `protobuf:"fixed64,4,opt,name=disk_percent,json=diskPercent,proto3" json:"disk_percent,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceStatusResponse) Reset() {
	*x = DeviceStatusResponse{}
	mi := &file_proto_v1_fleet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStatusResponse) ProtoMessage() {}

func (x *DeviceStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_fleet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStatusResponse.ProtoReflect.Descriptor instead.
func (*DeviceStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_fleet_proto_rawDescGZIP(), []int{6}
}

func (x *DeviceStatusResponse) GetDevice() *DeviceInfo {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *DeviceStatusResponse) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *DeviceStatusResponse) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *DeviceStatusResponse) GetDiskPercent() float64 {
	if x != nil {
		return x.DiskPercent
	}
	return 0
}

func (x *DeviceStatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_v1_fleet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_fleet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_fleet_proto_rawDescGZIP(), []int{7}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_v1_fleet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_fleet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_fleet_proto_rawDescGZIP(), []int{8}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type PairingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Certificate   []byte                 `protobuf:"bytes,3,opt,name=certificate,proto3" json:"certificate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairingRequest) Reset() {
	*x = PairingRequest{}
	mi := &file_proto_v1_fleet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairingRequest) ProtoMessage() {}

func (x *PairingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_fleet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairingRequest.ProtoReflect.Descriptor instead.
func (*PairingRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_fleet_proto_rawDescGZIP(), []int{9}
}

func (x *PairingRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PairingRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *PairingRequest) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

type PairingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	AssignedRole  string                 `protobuf:"bytes,2,opt,name=assigned_role,json=assignedRole,proto3" json:"assigned_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairingResponse) Reset() {
	*x = PairingResponse{}
	mi := &file_proto_v1_fleet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairingResponse) ProtoMessage() {}

func (x *PairingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_fleet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairingResponse.ProtoReflect.Descriptor instead.
func (*PairingResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_fleet_proto_rawDescGZIP(), []int{10}
}

func (x *PairingResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *PairingResponse) GetAssignedRole() string {
	if x != nil {
		return x.AssignedRole
	}
	return ""
}

type ScreenshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Display       int32                  `protobuf:"varint,1,opt,name=display,proto3" json:"display,omitempty"`
	Quality       int32                  `protobuf:"varint,2,opt,name=quality,proto3" json:"quality,omitempty"`
	Scale         float64                `protobuf:"fixed64,3,opt,name=scale,proto3" json:"scale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenshotRequest) Reset() {
	*x = ScreenshotRequest{}
	mi := &file_proto_v1_fleet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenshotRequest) ProtoMessage() {}

func (x *ScreenshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_fleet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenshotRequest.ProtoReflect.Descriptor instead.
func (*ScreenshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_fleet_proto_rawDescGZIP(), []int{11}
}

func (x *ScreenshotRequest) GetDisplay() int32 {
	if x != nil {
		return x.Display
	}
	return 0
}

func (x *ScreenshotRequest) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *ScreenshotRequest) GetScale() float64 {
	if x != nil {
		return x.Scale
	}
	return 0
}

type ScreenshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         []byte                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenshotResponse) Reset() {
	*x = ScreenshotResponse{}
	mi := &file_proto_v1_fleet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenshotResponse) ProtoMessage() {}

func (x *ScreenshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_fleet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenshotResponse.ProtoReflect.Descriptor instead.
func (*ScreenshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_fleet_proto_rawDescGZIP(), []int{12}
}

func (x *ScreenshotResponse) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ScreenshotResponse) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ScreenshotResponse) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ScreenshotResponse) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type CaptureWindowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowTitle   string                 `protobuf:"bytes,1,opt,name=window_title,json=windowTitle,proto3" json:"window_title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureWindowRequest) Reset() {
	*x = CaptureWindowRequest{}
	mi := &file_proto_v1_fleet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureWindowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureWindowRequest) ProtoMessage() {}

func (x *CaptureWindowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_fleet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureWindowRequest.ProtoReflect.Descriptor instead.
func (*CaptureWindowRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_fleet_proto_rawDescGZIP(), []int{13}
}

func (x *CaptureWindowRequest) GetWindowTitle() string {
	if x != nil {
		return x.WindowTitle
	}
	return ""
}

type CaptureWindowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         []byte                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	MatchedTitle  string                 `protobuf:"bytes,3,opt,name=matched_title,json=matchedTitle,proto3" json:"matched_title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureWindowResponse) Reset() {
	*x = CaptureWindowResponse{}
	mi := &file_proto_v1_fleet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureWindowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureWindowResponse) ProtoMessage() {}

func (x *CaptureWindowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_fleet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureWindowResponse.ProtoReflect.Descriptor instead.
func (*CaptureWindowResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_fleet_proto_rawDescGZIP(), []int{14}
}

func (x *CaptureWindowResponse) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *CaptureWindowResponse) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *CaptureWindowResponse) GetMatchedTitle() string {
	if x != nil {
		return x.MatchedTitle
	}
	return ""
}

type ListDisplaysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDisplaysRequest) Reset() {
	*x = ListDisplaysRequest{}
	mi := &file_proto_v1_fleet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDisplaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDisplaysRequest) ProtoMessage() {}

func (x *ListDisplaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_fleet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDisplaysRequest.ProtoReflect.Descriptor instead.
func (*ListDisplaysRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_fleet_proto_rawDescGZIP(), []int{15}
}

type ListDisplaysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Displays      []*DisplayInfo         `protobuf:"bytes,1,rep,name=displays,proto3" json:"displays,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDisplaysResponse) Reset() {
	*x = ListDisplaysResponse{}
	mi := &file_proto_v1_fleet_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDisplaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDisplaysResponse) ProtoMessage() {}

func (x *ListDisplaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_fleet_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDisplaysResponse.ProtoReflect.Descriptor instead.
func (*ListDisplaysResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_fleet_proto_rawDescGZIP(), []int{16}
}

func (x *ListDisplaysResponse) GetDisplays() []*DisplayInfo {
	if x != nil {
		return x.Displays
	}
	return nil
}

type DisplayInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Primary       bool                   `protobuf:"varint,5,opt,name=primary,proto3" json:"primary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisplayInfo) Reset() {
	*x = DisplayInfo{}
	mi := &file_proto_v1_fleet_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisplayInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayInfo) ProtoMessage() {}

func (x *DisplayInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_fleet_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplayInfo.ProtoReflect.Descriptor instead.
func (*DisplayInfo) Descriptor() ([]byte, []int) {
	return file_proto_v1_fleet_proto_rawDescGZIP(), []int{17}
}

func (x *DisplayInfo) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DisplayInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DisplayInfo) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *DisplayInfo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *DisplayInfo) GetPrimary() bool {
	if x != nil {
		return x.Primary
	}
	return false
}

var File_proto_v1_fleet_proto protoreflect.FileDescriptor

const file_proto_v1_fleet_proto_rawDesc = "" +
	"\n" +
	"\x14proto/v1/fleet.proto\x12\vsentinel.v1\"\x90\x01\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12 \n" +
	"\vcertificate\x18\x05 \x01(\fR\vcertificate\"`\n" +
	"\x10RegisterResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x120\n" +
	"\x14controller_device_id\x18\x02 \x01(\tR\x12controllerDeviceId\"\x14\n" +
	"\x12ListDevicesRequest\"H\n" +
	"\x13ListDevicesResponse\x121\n" +
	"\adevices\x18\x01 \x03(\v2\x17.sentinel.v1.DeviceInfoR\adevices\"\xd5\x01\n" +
	"\n" +
	"DeviceInfo\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12$\n" +
	"\x0elast_seen_unix\x18\a \x01(\x03R\flastSeenUnix\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\"2\n" +
	"\x13DeviceStatusRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"\xd9\x01\n" +
	"\x14DeviceStatusResponse\x12/\n" +
	"\x06device\x18\x01 \x01(\v2\x17.sentinel.v1.DeviceInfoR\x06device\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x01R\n" +
	"cpuPercent\x12%\n" +
	"\x0ememory_percent\x18\x03 \x01(\x01R\rmemoryPercent\x12!\n" +
	"\fdisk_percent\x18\x04 \x01(\x01R\vdiskPercent\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x03R\ruptimeSeconds\"\x0f\n" +
	"\rHealthRequest\"\x86\x01\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\"c\n" +
	"\x0ePairingRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12 \n" +
	"\vcertificate\x18\x03 \x01(\fR\vcertificate\"R\n" +
	"\x0fPairingResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rassigned_role\x18\x02 \x01(\tR\fassignedRole\"]\n" +
	"\x11ScreenshotRequest\x12\x18\n" +
	"\adisplay\x18\x01 \x01(\x05R\adisplay\x12\x18\n" +
	"\aquality\x18\x02 \x01(\x05R\aquality\x12\x14\n" +
	"\x05scale\x18\x03 \x01(\x01R\x05scale\"p\n" +
	"\x12ScreenshotResponse\x12\x14\n" +
	"\x05image\x18\x01 \x01(\fR\x05image\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\"9\n" +
	"\x14CaptureWindowRequest\x12!\n" +
	"\fwindow_title\x18\x01 \x01(\tR\vwindowTitle\"j\n" +
	"\x15CaptureWindowResponse\x12\x14\n" +
	"\x05image\x18\x01 \x01(\fR\x05image\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12#\n" +
	"\rmatched_title\x18\x03 \x01(\tR\fmatchedTitle\"\x15\n" +
	"\x13ListDisplaysRequest\"L\n" +
	"\x14ListDisplaysResponse\x124\n" +
	"\bdisplays\x18\x01 \x03(\v2\x18.sentinel.v1.DisplayInfoR\bdisplays\"\x7f\n" +
	"\vDisplayInfo\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12\x18\n" +
	"\aprimary\x18\x05 \x01(\bR\aprimary2\x8d\x03\n" +
	"\fFleetService\x12G\n" +
	"\bRegister\x12\x1c.sentinel.v1.RegisterRequest\x1a\x1d.sentinel.v1.RegisterResponse\x12P\n" +
	"\vListDevices\x12\x1f.sentinel.v1.ListDevicesRequest\x1a .sentinel.v1.ListDevicesResponse\x12S\n" +
	"\fDeviceStatus\x12 .sentinel.v1.DeviceStatusRequest\x1a!.sentinel.v1.DeviceStatusResponse\x12A\n" +
	"\x06Health\x12\x1a.sentinel.v1.HealthRequest\x1a\x1b.sentinel.v1.HealthResponse\x12J\n" +
	"\rAcceptPairing\x12\x1b.sentinel.v1.PairingRequest\x1a\x1c.sentinel.v1.PairingResponse2\x8c\x02\n" +
	"\x0eCaptureService\x12M\n" +
	"\n" +
	"Screenshot\x12\x1e.sentinel.v1.ScreenshotRequest\x1a\x1f.sentinel.v1.ScreenshotResponse\x12V\n" +
	"\rCaptureWindow\x12!.sentinel.v1.CaptureWindowRequest\x1a\".sentinel.v1.CaptureWindowResponse\x12S\n" +
	"\fListDisplays\x12 .sentinel.v1.ListDisplaysRequest\x1a!.sentinel.v1.ListDisplaysResponseB0Z.github.com/inovacc/sentinel/internal/api/v1;v1b\x06proto3"

var (
	file_proto_v1_fleet_proto_rawDescOnce sync.Once
	file_proto_v1_fleet_proto_rawDescData []byte
)

func file_proto_v1_fleet_proto_rawDescGZIP() []byte {
	file_proto_v1_fleet_proto_rawDescOnce.Do(func() {
		file_proto_v1_fleet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_fleet_proto_rawDesc), len(file_proto_v1_fleet_proto_rawDesc)))
	})
	return file_proto_v1_fleet_proto_rawDescData
}

var file_proto_v1_fleet_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_v1_fleet_proto_goTypes = []any{
	(*RegisterRequest)(nil),       // 0: sentinel.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 1: sentinel.v1.RegisterResponse
	(*ListDevicesRequest)(nil),    // 2: sentinel.v1.ListDevicesRequest
	(*ListDevicesResponse)(nil),   // 3: sentinel.v1.ListDevicesResponse
	(*DeviceInfo)(nil),            // 4: sentinel.v1.DeviceInfo
	(*DeviceStatusRequest)(nil),   // 5: sentinel.v1.DeviceStatusRequest
	(*DeviceStatusResponse)(nil),  // 6: sentinel.v1.DeviceStatusResponse
	(*HealthRequest)(nil),         // 7: sentinel.v1.HealthRequest
	(*HealthResponse)(nil),        // 8: sentinel.v1.HealthResponse
	(*PairingRequest)(nil),        // 9: sentinel.v1.PairingRequest
	(*PairingResponse)(nil),       // 10: sentinel.v1.PairingResponse
	(*ScreenshotRequest)(nil),     // 11: sentinel.v1.ScreenshotRequest
	(*ScreenshotResponse)(nil),    // 12: sentinel.v1.ScreenshotResponse
	(*CaptureWindowRequest)(nil),  // 13: sentinel.v1.CaptureWindowRequest
	(*CaptureWindowResponse)(nil), // 14: sentinel.v1.CaptureWindowResponse
	(*ListDisplaysRequest)(nil),   // 15: sentinel.v1.ListDisplaysRequest
	(*ListDisplaysResponse)(nil),  // 16: sentinel.v1.ListDisplaysResponse
	(*DisplayInfo)(nil),           // 17: sentinel.v1.DisplayInfo
}
var file_proto_v1_fleet_proto_depIdxs = []int32{
	4,  // 0: sentinel.v1.ListDevicesResponse.devices:type_name -> sentinel.v1.DeviceInfo
	4,  // 1: sentinel.v1.DeviceStatusResponse.device:type_name -> sentinel.v1.DeviceInfo
	17, // 2: sentinel.v1.ListDisplaysResponse.displays:type_name -> sentinel.v1.DisplayInfo
	0,  // 3: sentinel.v1.FleetService.Register:input_type -> sentinel.v1.RegisterRequest
	2,  // 4: sentinel.v1.FleetService.ListDevices:input_type -> sentinel.v1.ListDevicesRequest
	5,  // 5: sentinel.v1.FleetService.DeviceStatus:input_type -> sentinel.v1.DeviceStatusRequest
	7,  // 6: sentinel.v1.FleetService.Health:input_type -> sentinel.v1.HealthRequest
	9,  // 7: sentinel.v1.FleetService.AcceptPairing:input_type -> sentinel.v1.PairingRequest
	11, // 8: sentinel.v1.CaptureService.Screenshot:input_type -> sentinel.v1.ScreenshotRequest
	13, // 9: sentinel.v1.CaptureService.CaptureWindow:input_type -> sentinel.v1.CaptureWindowRequest
	15, // 10: sentinel.v1.CaptureService.ListDisplays:input_type -> sentinel.v1.ListDisplaysRequest
	1,  // 11: sentinel.v1.FleetService.Register:output_type -> sentinel.v1.RegisterResponse
	3,  // 12: sentinel.v1.FleetService.ListDevices:output_type -> sentinel.v1.ListDevicesResponse
	6,  // 13: sentinel.v1.FleetService.DeviceStatus:output_type -> sentinel.v1.DeviceStatusResponse
	8,  // 14: sentinel.v1.FleetService.Health:output_type -> sentinel.v1.HealthResponse
	10, // 15: sentinel.v1.FleetService.AcceptPairing:output_type -> sentinel.v1.PairingResponse
	12, // 16: sentinel.v1.CaptureService.Screenshot:output_type -> sentinel.v1.ScreenshotResponse
	14, // 17: sentinel.v1.CaptureService.CaptureWindow:output_type -> sentinel.v1.CaptureWindowResponse
	16, // 18: sentinel.v1.CaptureService.ListDisplays:output_type -> sentinel.v1.ListDisplaysResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_v1_fleet_proto_init() }
func file_proto_v1_fleet_proto_init() {
	if File_proto_v1_fleet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_fleet_proto_rawDesc), len(file_proto_v1_fleet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_v1_fleet_proto_goTypes,
		DependencyIndexes: file_proto_v1_fleet_proto_depIdxs,
		MessageInfos:      file_proto_v1_fleet_proto_msgTypes,
	}.Build()
	File_proto_v1_fleet_proto = out.File
	file_proto_v1_fleet_proto_goTypes = nil
	file_proto_v1_fleet_proto_depIdxs = nil
}
