// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/v1/payload.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PayloadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Action identifier (e.g., "ping", "sysinfo", "env.get", "file.stat").
	Action string `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	// JSON-encoded payload string.
	Payload string `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// Optional session ID for tracking.
	SessionId string `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Optional key-value metadata.
	Metadata      map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadRequest) Reset() {
	*x = PayloadRequest{}
	mi := &file_proto_v1_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadRequest) ProtoMessage() {}

func (x *PayloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadRequest.ProtoReflect.Descriptor instead.
func (*PayloadRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_payload_proto_rawDescGZIP(), []int{0}
}

func (x *PayloadRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PayloadRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *PayloadRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PayloadRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PayloadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Echo of the action that was processed.
	Action string `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	// JSON-encoded response string.
	Payload string `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// Whether the action succeeded.
	Success bool `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success is false.
	Error string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	// Processing duration in milliseconds.
	DurationMs    int64 `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadResponse) Reset() {
	*x = PayloadResponse{}
	mi := &file_proto_v1_payload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadResponse) ProtoMessage() {}

func (x *PayloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_payload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadResponse.ProtoReflect.Descriptor instead.
func (*PayloadResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_payload_proto_rawDescGZIP(), []int{1}
}

func (x *PayloadResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PayloadResponse) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *PayloadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PayloadResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PayloadResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type PayloadChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON-encoded chunk of data.
	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Whether this is the last chunk.
	Done bool `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	// Error message if the stream encountered an error.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadChunk) Reset() {
	*x = PayloadChunk{}
	mi := &file_proto_v1_payload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadChunk) ProtoMessage() {}

func (x *PayloadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_payload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadChunk.ProtoReflect.Descriptor instead.
func (*PayloadChunk) Descriptor() ([]byte, []int) {
	return file_proto_v1_payload_proto_rawDescGZIP(), []int{2}
}

func (x *PayloadChunk) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *PayloadChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *PayloadChunk) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_v1_payload_proto protoreflect.FileDescriptor

const file_proto_v1_payload_proto_rawDesc = "" +
	"\n" +
	"\x16proto/v1/payload.proto\x12\vsentinel.v1\"\xe5\x01\n" +
	"\x0ePayloadRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12E\n" +
	"\bmetadata\x18\x04 \x03(\v2).sentinel.v1.PayloadRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x94\x01\n" +
	"\x0fPayloadResponse\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x03R\n" +
	"durationMs\"L\n" +
	"\fPayloadChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\x9b\x01\n" +
	"\x0ePayloadService\x12A\n" +
	"\x04Send\x12\x1b.sentinel.v1.PayloadRequest\x1a\x1c.sentinel.v1.PayloadResponse\x12F\n" +
	"\n" +
	"SendStream\x12\x1b.sentinel.v1.PayloadRequest\x1a\x19.sentinel.v1.PayloadChunk0\x01B0Z.github.com/inovacc/sentinel/internal/api/v1;v1b\x06proto3"

var (
	file_proto_v1_payload_proto_rawDescOnce sync.Once
	file_proto_v1_payload_proto_rawDescData []byte
)

func file_proto_v1_payload_proto_rawDescGZIP() []byte {
	file_proto_v1_payload_proto_rawDescOnce.Do(func() {
		file_proto_v1_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_payload_proto_rawDesc), len(file_proto_v1_payload_proto_rawDesc)))
	})
	return file_proto_v1_payload_proto_rawDescData
}

var file_proto_v1_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_v1_payload_proto_goTypes = []any{
	(*PayloadRequest)(nil),  // 0: sentinel.v1.PayloadRequest
	(*PayloadResponse)(nil), // 1: sentinel.v1.PayloadResponse
	(*PayloadChunk)(nil),    // 2: sentinel.v1.PayloadChunk
	nil,                     // 3: sentinel.v1.PayloadRequest.MetadataEntry
}
var file_proto_v1_payload_proto_depIdxs = []int32{
	3, // 0: sentinel.v1.PayloadRequest.metadata:type_name -> sentinel.v1.PayloadRequest.MetadataEntry
	0, // 1: sentinel.v1.PayloadService.Send:input_type -> sentinel.v1.PayloadRequest
	0, // 2: sentinel.v1.PayloadService.SendStream:input_type -> sentinel.v1.PayloadRequest
	1, // 3: sentinel.v1.PayloadService.Send:output_type -> sentinel.v1.PayloadResponse
	2, // 4: sentinel.v1.PayloadService.SendStream:output_type -> sentinel.v1.PayloadChunk
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_v1_payload_proto_init() }
func file_proto_v1_payload_proto_init() {
	if File_proto_v1_payload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_payload_proto_rawDesc), len(file_proto_v1_payload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_payload_proto_goTypes,
		DependencyIndexes: file_proto_v1_payload_proto_depIdxs,
		MessageInfos:      file_proto_v1_payload_proto_msgTypes,
	}.Build()
	File_proto_v1_payload_proto = out.File
	file_proto_v1_payload_proto_goTypes = nil
	file_proto_v1_payload_proto_depIdxs = nil
}
