// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/v1/payload.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PayloadService_Send_FullMethodName       = "/sentinel.v1.PayloadService/Send"
	PayloadService_SendStream_FullMethodName = "/sentinel.v1.PayloadService/SendStream"
)

// PayloadServiceClient is the client API for PayloadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PayloadService handles structured JSON request/response communication.
type PayloadServiceClient interface {
	// Send a structured JSON payload and receive a JSON response.
	Send(ctx context.Context, in *PayloadRequest, opts ...grpc.CallOption) (*PayloadResponse, error)
	// Send a payload and receive streaming chunks (for long-running actions).
	SendStream(ctx context.Context, in *PayloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PayloadChunk], error)
}

type payloadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPayloadServiceClient(cc grpc.ClientConnInterface) PayloadServiceClient {
	return &payloadServiceClient{cc}
}

func (c *payloadServiceClient) Send(ctx context.Context, in *PayloadRequest, opts ...grpc.CallOption) (*PayloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayloadResponse)
	err := c.cc.Invoke(ctx, PayloadService_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payloadServiceClient) SendStream(ctx context.Context, in *PayloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PayloadChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PayloadService_ServiceDesc.Streams[0], PayloadService_SendStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PayloadRequest, PayloadChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PayloadService_SendStreamClient = grpc.ServerStreamingClient[PayloadChunk]

// PayloadServiceServer is the server API for PayloadService service.
// All implementations must embed UnimplementedPayloadServiceServer
// for forward compatibility.
//
// PayloadService handles structured JSON request/response communication.
type PayloadServiceServer interface {
	// Send a structured JSON payload and receive a JSON response.
	Send(context.Context, *PayloadRequest) (*PayloadResponse, error)
	// Send a payload and receive streaming chunks (for long-running actions).
	SendStream(*PayloadRequest, grpc.ServerStreamingServer[PayloadChunk]) error
	mustEmbedUnimplementedPayloadServiceServer()
}

// UnimplementedPayloadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPayloadServiceServer struct{}

func (UnimplementedPayloadServiceServer) Send(context.Context, *PayloadRequest) (*PayloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedPayloadServiceServer) SendStream(*PayloadRequest, grpc.ServerStreamingServer[PayloadChunk]) error {
	return status.Error(codes.Unimplemented, "method SendStream not implemented")
}
func (UnimplementedPayloadServiceServer) mustEmbedUnimplementedPayloadServiceServer() {}
func (UnimplementedPayloadServiceServer) testEmbeddedByValue()                        {}

// UnsafePayloadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PayloadServiceServer will
// result in compilation errors.
type UnsafePayloadServiceServer interface {
	mustEmbedUnimplementedPayloadServiceServer()
}

func RegisterPayloadServiceServer(s grpc.ServiceRegistrar, srv PayloadServiceServer) {
	// If the following call panics, it indicates UnimplementedPayloadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PayloadService_ServiceDesc, srv)
}

func _PayloadService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayloadServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayloadService_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayloadServiceServer).Send(ctx, req.(*PayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayloadService_SendStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PayloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PayloadServiceServer).SendStream(m, &grpc.GenericServerStream[PayloadRequest, PayloadChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PayloadService_SendStreamServer = grpc.ServerStreamingServer[PayloadChunk]

// PayloadService_ServiceDesc is the grpc.ServiceDesc for PayloadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PayloadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sentinel.v1.PayloadService",
	HandlerType: (*PayloadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _PayloadService_Send_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendStream",
			Handler:       _PayloadService_SendStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/v1/payload.proto",
}
