// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/v1/sentinel.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecOutput_Stream int32

const (
	ExecOutput_STDOUT ExecOutput_Stream = 0
	ExecOutput_STDERR ExecOutput_Stream = 1
)

// Enum value maps for ExecOutput_Stream.
var (
	ExecOutput_Stream_name = map[int32]string{
		0: "STDOUT",
		1: "STDERR",
	}
	ExecOutput_Stream_value = map[string]int32{
		"STDOUT": 0,
		"STDERR": 1,
	}
)

func (x ExecOutput_Stream) Enum() *ExecOutput_Stream {
	p := new(ExecOutput_Stream)
	*p = x
	return p
}

func (x ExecOutput_Stream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecOutput_Stream) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_sentinel_proto_enumTypes[0].Descriptor()
}

func (ExecOutput_Stream) Type() protoreflect.EnumType {
	return &file_proto_v1_sentinel_proto_enumTypes[0]
}

func (x ExecOutput_Stream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecOutput_Stream.Descriptor instead.
func (ExecOutput_Stream) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_sentinel_proto_rawDescGZIP(), []int{2, 0}
}

type ExecRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Command        string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args           []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	WorkingDir     string                 `protobuf:"bytes,3,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	Env            map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	SessionId      string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_proto_v1_sentinel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_sentinel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_sentinel_proto_rawDescGZIP(), []int{0}
}

func (x *ExecRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ExecRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ExecRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_proto_v1_sentinel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_sentinel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_sentinel_proto_rawDescGZIP(), []int{1}
}

func (x *ExecResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type ExecOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        ExecOutput_Stream      `protobuf:"varint,1,opt,name=stream,proto3,enum=sentinel.v1.ExecOutput_Stream" json:"stream,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Done          bool                   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecOutput) Reset() {
	*x = ExecOutput{}
	mi := &file_proto_v1_sentinel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecOutput) ProtoMessage() {}

func (x *ExecOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_sentinel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecOutput.ProtoReflect.Descriptor instead.
func (*ExecOutput) Descriptor() ([]byte, []int) {
	return file_proto_v1_sentinel_proto_rawDescGZIP(), []int{2}
}

func (x *ExecOutput) GetStream() ExecOutput_Stream {
	if x != nil {
		return x.Stream
	}
	return ExecOutput_STDOUT
}

func (x *ExecOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExecOutput) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ExecOutput) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_proto_v1_sentinel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_sentinel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_sentinel_proto_rawDescGZIP(), []int{3}
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReadFileRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadFileRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ReadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_proto_v1_sentinel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_sentinel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_sentinel_proto_rawDescGZIP(), []int{4}
}

func (x *ReadFileResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ReadFileResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ReadFileResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type WriteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	CreateDirs    bool                   `protobuf:"varint,3,opt,name=create_dirs,json=createDirs,proto3" json:"create_dirs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_proto_v1_sentinel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_sentinel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_sentinel_proto_rawDescGZIP(), []int{5}
}

func (x *WriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *WriteFileRequest) GetCreateDirs() bool {
	if x != nil {
		return x.CreateDirs
	}
	return false
}

type WriteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten  int64                  `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResponse) Reset() {
	*x = WriteFileResponse{}
	mi := &file_proto_v1_sentinel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResponse) ProtoMessage() {}

func (x *WriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_sentinel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResponse.ProtoReflect.Descriptor instead.
func (*WriteFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_sentinel_proto_rawDescGZIP(), []int{6}
}

func (x *WriteFileResponse) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

type ListDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Recursive     bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirRequest) Reset() {
	*x = ListDirRequest{}
	mi := &file_proto_v1_sentinel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirRequest) ProtoMessage() {}

func (x *ListDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_sentinel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirRequest.ProtoReflect.Descriptor instead.
func (*ListDirRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_sentinel_proto_rawDescGZIP(), []int{7}
}

func (x *ListDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListDirRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type ListDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*FileEntry           `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirResponse) Reset() {
	*x = ListDirResponse{}
	mi := &file_proto_v1_sentinel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirResponse) ProtoMessage() {}

func (x *ListDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_sentinel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirResponse.ProtoReflect.Descriptor instead.
func (*ListDirResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_sentinel_proto_rawDescGZIP(), []int{8}
}

func (x *ListDirResponse) GetEntries() []*FileEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type FileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	IsDir         bool                   `protobuf:"varint,3,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	ModifiedUnix  int64                  `protobuf:"varint,5,opt,name=modified_unix,json=modifiedUnix,proto3" json:"modified_unix,omitempty"`
	Mode          string                 `protobuf:"bytes,6,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_proto_v1_sentinel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_sentinel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_proto_v1_sentinel_proto_rawDescGZIP(), []int{9}
}

func (x *FileEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileEntry) GetModifiedUnix() int64 {
	if x != nil {
		return x.ModifiedUnix
	}
	return 0
}

func (x *FileEntry) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type UploadChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetPath    string                 `protobuf:"bytes,1,opt,name=target_path,json=targetPath,proto3" json:"target_path,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	IsLast        bool                   `protobuf:"varint,3,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadChunk) Reset() {
	*x = UploadChunk{}
	mi := &file_proto_v1_sentinel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunk) ProtoMessage() {}

func (x *UploadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_sentinel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunk.ProtoReflect.Descriptor instead.
func (*UploadChunk) Descriptor() ([]byte, []int) {
	return file_proto_v1_sentinel_proto_rawDescGZIP(), []int{10}
}

func (x *UploadChunk) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

func (x *UploadChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalBytes    int64                  `protobuf:"varint,1,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_proto_v1_sentinel_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_sentinel_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_sentinel_proto_rawDescGZIP(), []int{11}
}

func (x *UploadResponse) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *UploadResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_proto_v1_sentinel_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_sentinel_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_sentinel_proto_rawDescGZIP(), []int{12}
}

func (x *DownloadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DownloadChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	IsLast        bool                   `protobuf:"varint,2,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadChunk) Reset() {
	*x = DownloadChunk{}
	mi := &file_proto_v1_sentinel_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadChunk) ProtoMessage() {}

func (x *DownloadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_sentinel_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadChunk.ProtoReflect.Descriptor instead.
func (*DownloadChunk) Descriptor() ([]byte, []int) {
	return file_proto_v1_sentinel_proto_rawDescGZIP(), []int{13}
}

func (x *DownloadChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DownloadChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_v1_sentinel_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_sentinel_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_sentinel_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_v1_sentinel_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_sentinel_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_sentinel_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type GlobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       string                 `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	BasePath      string                 `protobuf:"bytes,2,opt,name=base_path,json=basePath,proto3" json:"base_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobRequest) Reset() {
	*x = GlobRequest{}
	mi := &file_proto_v1_sentinel_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobRequest) ProtoMessage() {}

func (x *GlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_sentinel_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobRequest.ProtoReflect.Descriptor instead.
func (*GlobRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_sentinel_proto_rawDescGZIP(), []int{16}
}

func (x *GlobRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *GlobRequest) GetBasePath() string {
	if x != nil {
		return x.BasePath
	}
	return ""
}

type GlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []string               `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobResponse) Reset() {
	*x = GlobResponse{}
	mi := &file_proto_v1_sentinel_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobResponse) ProtoMessage() {}

func (x *GlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_sentinel_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobResponse.ProtoReflect.Descriptor instead.
func (*GlobResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_sentinel_proto_rawDescGZIP(), []int{17}
}

func (x *GlobResponse) GetMatches() []string {
	if x != nil {
		return x.Matches
	}
	return nil
}

type GrepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       string                 `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Recursive     bool                   `protobuf:"varint,3,opt,name=recursive,proto3" json:"recursive,omitempty"`
	IgnoreCase    bool                   `protobuf:"varint,4,opt,name=ignore_case,json=ignoreCase,proto3" json:"ignore_case,omitempty"`
	ContextLines  int32                  `protobuf:"varint,5,opt,name=context_lines,json=contextLines,proto3" json:"context_lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrepRequest) Reset() {
	*x = GrepRequest{}
	mi := &file_proto_v1_sentinel_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrepRequest) ProtoMessage() {}

func (x *GrepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_sentinel_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrepRequest.ProtoReflect.Descriptor instead.
func (*GrepRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_sentinel_proto_rawDescGZIP(), []int{18}
}

func (x *GrepRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *GrepRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GrepRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

func (x *GrepRequest) GetIgnoreCase() bool {
	if x != nil {
		return x.IgnoreCase
	}
	return false
}

func (x *GrepRequest) GetContextLines() int32 {
	if x != nil {
		return x.ContextLines
	}
	return 0
}

type GrepResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*GrepMatch           `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrepResponse) Reset() {
	*x = GrepResponse{}
	mi := &file_proto_v1_sentinel_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrepResponse) ProtoMessage() {}

func (x *GrepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_sentinel_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrepResponse.ProtoReflect.Descriptor instead.
func (*GrepResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_sentinel_proto_rawDescGZIP(), []int{19}
}

func (x *GrepResponse) GetMatches() []*GrepMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

type GrepMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Line          int32                  `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	ContextBefore []string               `protobuf:"bytes,4,rep,name=context_before,json=contextBefore,proto3" json:"context_before,omitempty"`
	ContextAfter  []string               `protobuf:"bytes,5,rep,name=context_after,json=contextAfter,proto3" json:"context_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrepMatch) Reset() {
	*x = GrepMatch{}
	mi := &file_proto_v1_sentinel_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrepMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrepMatch) ProtoMessage() {}

func (x *GrepMatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_sentinel_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrepMatch.ProtoReflect.Descriptor instead.
func (*GrepMatch) Descriptor() ([]byte, []int) {
	return file_proto_v1_sentinel_proto_rawDescGZIP(), []int{20}
}

func (x *GrepMatch) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *GrepMatch) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *GrepMatch) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GrepMatch) GetContextBefore() []string {
	if x != nil {
		return x.ContextBefore
	}
	return nil
}

func (x *GrepMatch) GetContextAfter() []string {
	if x != nil {
		return x.ContextAfter
	}
	return nil
}

var File_proto_v1_sentinel_proto protoreflect.FileDescriptor

const file_proto_v1_sentinel_proto_rawDesc = "" +
	"\n" +
	"\x17proto/v1/sentinel.proto\x12\vsentinel.v1\"\x91\x02\n" +
	"\vExecRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12\x1f\n" +
	"\vworking_dir\x18\x03 \x01(\tR\n" +
	"workingDir\x123\n" +
	"\x03env\x18\x04 \x03(\v2!.sentinel.v1.ExecRequest.EnvEntryR\x03env\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"|\n" +
	"\fExecResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\"\xab\x01\n" +
	"\n" +
	"ExecOutput\x126\n" +
	"\x06stream\x18\x01 \x01(\x0e2\x1e.sentinel.v1.ExecOutput.StreamR\x06stream\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\" \n" +
	"\x06Stream\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x00\x12\n" +
	"\n" +
	"\x06STDERR\x10\x01\"S\n" +
	"\x0fReadFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\"]\n" +
	"\x10ReadFileResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\"a\n" +
	"\x10WriteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x1f\n" +
	"\vcreate_dirs\x18\x03 \x01(\bR\n" +
	"createDirs\"8\n" +
	"\x11WriteFileResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x03R\fbytesWritten\"B\n" +
	"\x0eListDirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\"C\n" +
	"\x0fListDirResponse\x120\n" +
	"\aentries\x18\x01 \x03(\v2\x16.sentinel.v1.FileEntryR\aentries\"\x97\x01\n" +
	"\tFileEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x15\n" +
	"\x06is_dir\x18\x03 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12#\n" +
	"\rmodified_unix\x18\x05 \x01(\x03R\fmodifiedUnix\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\tR\x04mode\"[\n" +
	"\vUploadChunk\x12\x1f\n" +
	"\vtarget_path\x18\x01 \x01(\tR\n" +
	"targetPath\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x17\n" +
	"\ais_last\x18\x03 \x01(\bR\x06isLast\"E\n" +
	"\x0eUploadResponse\x12\x1f\n" +
	"\vtotal_bytes\x18\x01 \x01(\x03R\n" +
	"totalBytes\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"%\n" +
	"\x0fDownloadRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"<\n" +
	"\rDownloadChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x17\n" +
	"\ais_last\x18\x02 \x01(\bR\x06isLast\"#\n" +
	"\rDeleteRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"D\n" +
	"\vGlobRequest\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\x12\x1b\n" +
	"\tbase_path\x18\x02 \x01(\tR\bbasePath\"(\n" +
	"\fGlobResponse\x12\x18\n" +
	"\amatches\x18\x01 \x03(\tR\amatches\"\x9f\x01\n" +
	"\vGrepRequest\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x03 \x01(\bR\trecursive\x12\x1f\n" +
	"\vignore_case\x18\x04 \x01(\bR\n" +
	"ignoreCase\x12#\n" +
	"\rcontext_lines\x18\x05 \x01(\x05R\fcontextLines\"@\n" +
	"\fGrepResponse\x120\n" +
	"\amatches\x18\x01 \x03(\v2\x16.sentinel.v1.GrepMatchR\amatches\"\x93\x01\n" +
	"\tGrepMatch\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x12\x12\n" +
	"\x04line\x18\x02 \x01(\x05R\x04line\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12%\n" +
	"\x0econtext_before\x18\x04 \x03(\tR\rcontextBefore\x12#\n" +
	"\rcontext_after\x18\x05 \x03(\tR\fcontextAfter2\x8d\x01\n" +
	"\vExecService\x12;\n" +
	"\x04Exec\x12\x18.sentinel.v1.ExecRequest\x1a\x19.sentinel.v1.ExecResponse\x12A\n" +
	"\n" +
	"ExecStream\x12\x18.sentinel.v1.ExecRequest\x1a\x17.sentinel.v1.ExecOutput0\x012\xb6\x04\n" +
	"\x11FileSystemService\x12G\n" +
	"\bReadFile\x12\x1c.sentinel.v1.ReadFileRequest\x1a\x1d.sentinel.v1.ReadFileResponse\x12J\n" +
	"\tWriteFile\x12\x1d.sentinel.v1.WriteFileRequest\x1a\x1e.sentinel.v1.WriteFileResponse\x12D\n" +
	"\aListDir\x12\x1b.sentinel.v1.ListDirRequest\x1a\x1c.sentinel.v1.ListDirResponse\x12A\n" +
	"\x06Upload\x12\x18.sentinel.v1.UploadChunk\x1a\x1b.sentinel.v1.UploadResponse(\x01\x12F\n" +
	"\bDownload\x12\x1c.sentinel.v1.DownloadRequest\x1a\x1a.sentinel.v1.DownloadChunk0\x01\x12A\n" +
	"\x06Delete\x12\x1a.sentinel.v1.DeleteRequest\x1a\x1b.sentinel.v1.DeleteResponse\x12;\n" +
	"\x04Glob\x12\x18.sentinel.v1.GlobRequest\x1a\x19.sentinel.v1.GlobResponse\x12;\n" +
	"\x04Grep\x12\x18.sentinel.v1.GrepRequest\x1a\x19.sentinel.v1.GrepResponseB0Z.github.com/inovacc/sentinel/internal/api/v1;v1b\x06proto3"

var (
	file_proto_v1_sentinel_proto_rawDescOnce sync.Once
	file_proto_v1_sentinel_proto_rawDescData []byte
)

func file_proto_v1_sentinel_proto_rawDescGZIP() []byte {
	file_proto_v1_sentinel_proto_rawDescOnce.Do(func() {
		file_proto_v1_sentinel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_sentinel_proto_rawDesc), len(file_proto_v1_sentinel_proto_rawDesc)))
	})
	return file_proto_v1_sentinel_proto_rawDescData
}

var file_proto_v1_sentinel_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_v1_sentinel_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_v1_sentinel_proto_goTypes = []any{
	(ExecOutput_Stream)(0),    // 0: sentinel.v1.ExecOutput.Stream
	(*ExecRequest)(nil),       // 1: sentinel.v1.ExecRequest
	(*ExecResponse)(nil),      // 2: sentinel.v1.ExecResponse
	(*ExecOutput)(nil),        // 3: sentinel.v1.ExecOutput
	(*ReadFileRequest)(nil),   // 4: sentinel.v1.ReadFileRequest
	(*ReadFileResponse)(nil),  // 5: sentinel.v1.ReadFileResponse
	(*WriteFileRequest)(nil),  // 6: sentinel.v1.WriteFileRequest
	(*WriteFileResponse)(nil), // 7: sentinel.v1.WriteFileResponse
	(*ListDirRequest)(nil),    // 8: sentinel.v1.ListDirRequest
	(*ListDirResponse)(nil),   // 9: sentinel.v1.ListDirResponse
	(*FileEntry)(nil),         // 10: sentinel.v1.FileEntry
	(*UploadChunk)(nil),       // 11: sentinel.v1.UploadChunk
	(*UploadResponse)(nil),    // 12: sentinel.v1.UploadResponse
	(*DownloadRequest)(nil),   // 13: sentinel.v1.DownloadRequest
	(*DownloadChunk)(nil),     // 14: sentinel.v1.DownloadChunk
	(*DeleteRequest)(nil),     // 15: sentinel.v1.DeleteRequest
	(*DeleteResponse)(nil),    // 16: sentinel.v1.DeleteResponse
	(*GlobRequest)(nil),       // 17: sentinel.v1.GlobRequest
	(*GlobResponse)(nil),      // 18: sentinel.v1.GlobResponse
	(*GrepRequest)(nil),       // 19: sentinel.v1.GrepRequest
	(*GrepResponse)(nil),      // 20: sentinel.v1.GrepResponse
	(*GrepMatch)(nil),         // 21: sentinel.v1.GrepMatch
	nil,                       // 22: sentinel.v1.ExecRequest.EnvEntry
}
var file_proto_v1_sentinel_proto_depIdxs = []int32{
	22, // 0: sentinel.v1.ExecRequest.env:type_name -> sentinel.v1.ExecRequest.EnvEntry
	0,  // 1: sentinel.v1.ExecOutput.stream:type_name -> sentinel.v1.ExecOutput.Stream
	10, // 2: sentinel.v1.ListDirResponse.entries:type_name -> sentinel.v1.FileEntry
	21, // 3: sentinel.v1.GrepResponse.matches:type_name -> sentinel.v1.GrepMatch
	1,  // 4: sentinel.v1.ExecService.Exec:input_type -> sentinel.v1.ExecRequest
	1,  // 5: sentinel.v1.ExecService.ExecStream:input_type -> sentinel.v1.ExecRequest
	4,  // 6: sentinel.v1.FileSystemService.ReadFile:input_type -> sentinel.v1.ReadFileRequest
	6,  // 7: sentinel.v1.FileSystemService.WriteFile:input_type -> sentinel.v1.WriteFileRequest
	8,  // 8: sentinel.v1.FileSystemService.ListDir:input_type -> sentinel.v1.ListDirRequest
	11, // 9: sentinel.v1.FileSystemService.Upload:input_type -> sentinel.v1.UploadChunk
	13, // 10: sentinel.v1.FileSystemService.Download:input_type -> sentinel.v1.DownloadRequest
	15, // 11: sentinel.v1.FileSystemService.Delete:input_type -> sentinel.v1.DeleteRequest
	17, // 12: sentinel.v1.FileSystemService.Glob:input_type -> sentinel.v1.GlobRequest
	19, // 13: sentinel.v1.FileSystemService.Grep:input_type -> sentinel.v1.GrepRequest
	2,  // 14: sentinel.v1.ExecService.Exec:output_type -> sentinel.v1.ExecResponse
	3,  // 15: sentinel.v1.ExecService.ExecStream:output_type -> sentinel.v1.ExecOutput
	5,  // 16: sentinel.v1.FileSystemService.ReadFile:output_type -> sentinel.v1.ReadFileResponse
	7,  // 17: sentinel.v1.FileSystemService.WriteFile:output_type -> sentinel.v1.WriteFileResponse
	9,  // 18: sentinel.v1.FileSystemService.ListDir:output_type -> sentinel.v1.ListDirResponse
	12, // 19: sentinel.v1.FileSystemService.Upload:output_type -> sentinel.v1.UploadResponse
	14, // 20: sentinel.v1.FileSystemService.Download:output_type -> sentinel.v1.DownloadChunk
	16, // 21: sentinel.v1.FileSystemService.Delete:output_type -> sentinel.v1.DeleteResponse
	18, // 22: sentinel.v1.FileSystemService.Glob:output_type -> sentinel.v1.GlobResponse
	20, // 23: sentinel.v1.FileSystemService.Grep:output_type -> sentinel.v1.GrepResponse
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_v1_sentinel_proto_init() }
func file_proto_v1_sentinel_proto_init() {
	if File_proto_v1_sentinel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_sentinel_proto_rawDesc), len(file_proto_v1_sentinel_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_v1_sentinel_proto_goTypes,
		DependencyIndexes: file_proto_v1_sentinel_proto_depIdxs,
		EnumInfos:         file_proto_v1_sentinel_proto_enumTypes,
		MessageInfos:      file_proto_v1_sentinel_proto_msgTypes,
	}.Build()
	File_proto_v1_sentinel_proto = out.File
	file_proto_v1_sentinel_proto_goTypes = nil
	file_proto_v1_sentinel_proto_depIdxs = nil
}
