// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/v1/session.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ProjectName   string                 `protobuf:"bytes,2,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	WorkingDir    string                 `protobuf:"bytes,4,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	Env           map[string]string      `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_proto_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *CreateSessionRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *CreateSessionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateSessionRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *CreateSessionRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SandboxPath   string                 `protobuf:"bytes,3,opt,name=sandbox_path,json=sandboxPath,proto3" json:"sandbox_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_proto_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_session_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateSessionResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *CreateSessionResponse) GetSandboxPath() string {
	if x != nil {
		return x.SandboxPath
	}
	return ""
}

type ResumeSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeSessionRequest) Reset() {
	*x = ResumeSessionRequest{}
	mi := &file_proto_v1_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeSessionRequest) ProtoMessage() {}

func (x *ResumeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeSessionRequest.ProtoReflect.Descriptor instead.
func (*ResumeSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_session_proto_rawDescGZIP(), []int{2}
}

func (x *ResumeSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ResumeSessionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Context        *SessionContext        `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	ErrorInfo      string                 `protobuf:"bytes,4,opt,name=error_info,json=errorInfo,proto3" json:"error_info,omitempty"`
	LastCheckpoint *SessionCheckpoint     `protobuf:"bytes,5,opt,name=last_checkpoint,json=lastCheckpoint,proto3" json:"last_checkpoint,omitempty"`
	RecentEvents   []*SessionEvent        `protobuf:"bytes,6,rep,name=recent_events,json=recentEvents,proto3" json:"recent_events,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResumeSessionResponse) Reset() {
	*x = ResumeSessionResponse{}
	mi := &file_proto_v1_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeSessionResponse) ProtoMessage() {}

func (x *ResumeSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeSessionResponse.ProtoReflect.Descriptor instead.
func (*ResumeSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_session_proto_rawDescGZIP(), []int{3}
}

func (x *ResumeSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ResumeSessionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ResumeSessionResponse) GetContext() *SessionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ResumeSessionResponse) GetErrorInfo() string {
	if x != nil {
		return x.ErrorInfo
	}
	return ""
}

func (x *ResumeSessionResponse) GetLastCheckpoint() *SessionCheckpoint {
	if x != nil {
		return x.LastCheckpoint
	}
	return nil
}

func (x *ResumeSessionResponse) GetRecentEvents() []*SessionEvent {
	if x != nil {
		return x.RecentEvents
	}
	return nil
}

type PauseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseSessionRequest) Reset() {
	*x = PauseSessionRequest{}
	mi := &file_proto_v1_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseSessionRequest) ProtoMessage() {}

func (x *PauseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseSessionRequest.ProtoReflect.Descriptor instead.
func (*PauseSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_session_proto_rawDescGZIP(), []int{4}
}

func (x *PauseSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PauseSessionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PauseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	CheckpointId  string                 `protobuf:"bytes,2,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseSessionResponse) Reset() {
	*x = PauseSessionResponse{}
	mi := &file_proto_v1_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseSessionResponse) ProtoMessage() {}

func (x *PauseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseSessionResponse.ProtoReflect.Descriptor instead.
func (*PauseSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_session_proto_rawDescGZIP(), []int{5}
}

func (x *PauseSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PauseSessionResponse) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

type SessionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStatusRequest) Reset() {
	*x = SessionStatusRequest{}
	mi := &file_proto_v1_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStatusRequest) ProtoMessage() {}

func (x *SessionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStatusRequest.ProtoReflect.Descriptor instead.
func (*SessionStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_session_proto_rawDescGZIP(), []int{6}
}

func (x *SessionStatusRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DeviceId        string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ResumedAt       int64                  `protobuf:"varint,6,opt,name=resumed_at,json=resumedAt,proto3" json:"resumed_at,omitempty"`
	Context         *SessionContext        `protobuf:"bytes,7,opt,name=context,proto3" json:"context,omitempty"`
	ErrorInfo       string                 `protobuf:"bytes,8,opt,name=error_info,json=errorInfo,proto3" json:"error_info,omitempty"`
	Metadata        string                 `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"`
	EventCount      int32                  `protobuf:"varint,10,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	CheckpointCount int32                  `protobuf:"varint,11,opt,name=checkpoint_count,json=checkpointCount,proto3" json:"checkpoint_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SessionStatusResponse) Reset() {
	*x = SessionStatusResponse{}
	mi := &file_proto_v1_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStatusResponse) ProtoMessage() {}

func (x *SessionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStatusResponse.ProtoReflect.Descriptor instead.
func (*SessionStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_session_proto_rawDescGZIP(), []int{7}
}

func (x *SessionStatusResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionStatusResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SessionStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SessionStatusResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SessionStatusResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *SessionStatusResponse) GetResumedAt() int64 {
	if x != nil {
		return x.ResumedAt
	}
	return 0
}

func (x *SessionStatusResponse) GetContext() *SessionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *SessionStatusResponse) GetErrorInfo() string {
	if x != nil {
		return x.ErrorInfo
	}
	return ""
}

func (x *SessionStatusResponse) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *SessionStatusResponse) GetEventCount() int32 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *SessionStatusResponse) GetCheckpointCount() int32 {
	if x != nil {
		return x.CheckpointCount
	}
	return 0
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	StatusFilter  string                 `protobuf:"bytes,2,opt,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_proto_v1_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_session_proto_rawDescGZIP(), []int{8}
}

func (x *ListSessionsRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ListSessionsRequest) GetStatusFilter() string {
	if x != nil {
		return x.StatusFilter
	}
	return ""
}

func (x *ListSessionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionSummary      `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_proto_v1_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_session_proto_rawDescGZIP(), []int{9}
}

func (x *ListSessionsResponse) GetSessions() []*SessionSummary {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type SessionSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ProjectName   string                 `protobuf:"bytes,4,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ErrorInfo     string                 `protobuf:"bytes,7,opt,name=error_info,json=errorInfo,proto3" json:"error_info,omitempty"`
	EventCount    int32                  `protobuf:"varint,8,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionSummary) Reset() {
	*x = SessionSummary{}
	mi := &file_proto_v1_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionSummary) ProtoMessage() {}

func (x *SessionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionSummary.ProtoReflect.Descriptor instead.
func (*SessionSummary) Descriptor() ([]byte, []int) {
	return file_proto_v1_session_proto_rawDescGZIP(), []int{10}
}

func (x *SessionSummary) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionSummary) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SessionSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SessionSummary) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *SessionSummary) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SessionSummary) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *SessionSummary) GetErrorInfo() string {
	if x != nil {
		return x.ErrorInfo
	}
	return ""
}

func (x *SessionSummary) GetEventCount() int32 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

type DestroySessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroySessionRequest) Reset() {
	*x = DestroySessionRequest{}
	mi := &file_proto_v1_session_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroySessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroySessionRequest) ProtoMessage() {}

func (x *DestroySessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_session_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroySessionRequest.ProtoReflect.Descriptor instead.
func (*DestroySessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_session_proto_rawDescGZIP(), []int{11}
}

func (x *DestroySessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DestroySessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroySessionResponse) Reset() {
	*x = DestroySessionResponse{}
	mi := &file_proto_v1_session_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroySessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroySessionResponse) ProtoMessage() {}

func (x *DestroySessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_session_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroySessionResponse.ProtoReflect.Descriptor instead.
func (*DestroySessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_session_proto_rawDescGZIP(), []int{12}
}

func (x *DestroySessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointRequest) Reset() {
	*x = CheckpointRequest{}
	mi := &file_proto_v1_session_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointRequest) ProtoMessage() {}

func (x *CheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_session_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointRequest.ProtoReflect.Descriptor instead.
func (*CheckpointRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_session_proto_rawDescGZIP(), []int{13}
}

func (x *CheckpointRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CheckpointRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckpointId  string                 `protobuf:"bytes,1,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointResponse) Reset() {
	*x = CheckpointResponse{}
	mi := &file_proto_v1_session_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointResponse) ProtoMessage() {}

func (x *CheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_session_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointResponse.ProtoReflect.Descriptor instead.
func (*CheckpointResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_session_proto_rawDescGZIP(), []int{14}
}

func (x *CheckpointResponse) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *CheckpointResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_v1_session_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_session_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_session_proto_rawDescGZIP(), []int{15}
}

func (x *HeartbeatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alive         bool                   `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_v1_session_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_session_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_session_proto_rawDescGZIP(), []int{16}
}

func (x *HeartbeatResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *HeartbeatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SessionContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkingDir    string                 `protobuf:"bytes,1,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	Env           map[string]string      `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LastCommand   string                 `protobuf:"bytes,3,opt,name=last_command,json=lastCommand,proto3" json:"last_command,omitempty"`
	LastOutput    string                 `protobuf:"bytes,4,opt,name=last_output,json=lastOutput,proto3" json:"last_output,omitempty"`
	LastExitCode  int32                  `protobuf:"varint,5,opt,name=last_exit_code,json=lastExitCode,proto3" json:"last_exit_code,omitempty"`
	ProjectName   string                 `protobuf:"bytes,6,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionContext) Reset() {
	*x = SessionContext{}
	mi := &file_proto_v1_session_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionContext) ProtoMessage() {}

func (x *SessionContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_session_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionContext.ProtoReflect.Descriptor instead.
func (*SessionContext) Descriptor() ([]byte, []int) {
	return file_proto_v1_session_proto_rawDescGZIP(), []int{17}
}

func (x *SessionContext) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *SessionContext) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *SessionContext) GetLastCommand() string {
	if x != nil {
		return x.LastCommand
	}
	return ""
}

func (x *SessionContext) GetLastOutput() string {
	if x != nil {
		return x.LastOutput
	}
	return ""
}

func (x *SessionContext) GetLastExitCode() int32 {
	if x != nil {
		return x.LastExitCode
	}
	return 0
}

func (x *SessionContext) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

type SessionCheckpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	State         *SessionContext        `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionCheckpoint) Reset() {
	*x = SessionCheckpoint{}
	mi := &file_proto_v1_session_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCheckpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCheckpoint) ProtoMessage() {}

func (x *SessionCheckpoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_session_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCheckpoint.ProtoReflect.Descriptor instead.
func (*SessionCheckpoint) Descriptor() ([]byte, []int) {
	return file_proto_v1_session_proto_rawDescGZIP(), []int{18}
}

func (x *SessionCheckpoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionCheckpoint) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SessionCheckpoint) GetState() *SessionContext {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *SessionCheckpoint) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type SessionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Sequence      int32                  `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEvent) Reset() {
	*x = SessionEvent{}
	mi := &file_proto_v1_session_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEvent) ProtoMessage() {}

func (x *SessionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_session_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEvent.ProtoReflect.Descriptor instead.
func (*SessionEvent) Descriptor() ([]byte, []int) {
	return file_proto_v1_session_proto_rawDescGZIP(), []int{19}
}

func (x *SessionEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SessionEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *SessionEvent) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *SessionEvent) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

var File_proto_v1_session_proto protoreflect.FileDescriptor

const file_proto_v1_session_proto_rawDesc = "" +
	"\n" +
	"\x16proto/v1/session.proto\x12\vsentinel.v1\"\x8f\x02\n" +
	"\x14CreateSessionRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12!\n" +
	"\fproject_name\x18\x02 \x01(\tR\vprojectName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vworking_dir\x18\x04 \x01(\tR\n" +
	"workingDir\x12<\n" +
	"\x03env\x18\x05 \x03(\v2*.sentinel.v1.CreateSessionRequest.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"v\n" +
	"\x15CreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12!\n" +
	"\fsandbox_path\x18\x03 \x01(\tR\vsandboxPath\"5\n" +
	"\x14ResumeSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xad\x02\n" +
	"\x15ResumeSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x125\n" +
	"\acontext\x18\x03 \x01(\v2\x1b.sentinel.v1.SessionContextR\acontext\x12\x1d\n" +
	"\n" +
	"error_info\x18\x04 \x01(\tR\terrorInfo\x12G\n" +
	"\x0flast_checkpoint\x18\x05 \x01(\v2\x1e.sentinel.v1.SessionCheckpointR\x0elastCheckpoint\x12>\n" +
	"\rrecent_events\x18\x06 \x03(\v2\x19.sentinel.v1.SessionEventR\frecentEvents\"L\n" +
	"\x13PauseSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"U\n" +
	"\x14PauseSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rcheckpoint_id\x18\x02 \x01(\tR\fcheckpointId\"5\n" +
	"\x14SessionStatusRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x86\x03\n" +
	"\x15SessionStatusResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"resumed_at\x18\x06 \x01(\x03R\tresumedAt\x125\n" +
	"\acontext\x18\a \x01(\v2\x1b.sentinel.v1.SessionContextR\acontext\x12\x1d\n" +
	"\n" +
	"error_info\x18\b \x01(\tR\terrorInfo\x12\x1a\n" +
	"\bmetadata\x18\t \x01(\tR\bmetadata\x12\x1f\n" +
	"\vevent_count\x18\n" +
	" \x01(\x05R\n" +
	"eventCount\x12)\n" +
	"\x10checkpoint_count\x18\v \x01(\x05R\x0fcheckpointCount\"m\n" +
	"\x13ListSessionsRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12#\n" +
	"\rstatus_filter\x18\x02 \x01(\tR\fstatusFilter\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"O\n" +
	"\x14ListSessionsResponse\x127\n" +
	"\bsessions\x18\x01 \x03(\v2\x1b.sentinel.v1.SessionSummaryR\bsessions\"\x85\x02\n" +
	"\x0eSessionSummary\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\fproject_name\x18\x04 \x01(\tR\vprojectName\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"error_info\x18\a \x01(\tR\terrorInfo\x12\x1f\n" +
	"\vevent_count\x18\b \x01(\x05R\n" +
	"eventCount\"6\n" +
	"\x15DestroySessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"2\n" +
	"\x16DestroySessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"T\n" +
	"\x11CheckpointRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"W\n" +
	"\x12CheckpointResponse\x12#\n" +
	"\rcheckpoint_id\x18\x01 \x01(\tR\fcheckpointId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"1\n" +
	"\x10HeartbeatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"A\n" +
	"\x11HeartbeatResponse\x12\x14\n" +
	"\x05alive\x18\x01 \x01(\bR\x05alive\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xae\x02\n" +
	"\x0eSessionContext\x12\x1f\n" +
	"\vworking_dir\x18\x01 \x01(\tR\n" +
	"workingDir\x126\n" +
	"\x03env\x18\x02 \x03(\v2$.sentinel.v1.SessionContext.EnvEntryR\x03env\x12!\n" +
	"\flast_command\x18\x03 \x01(\tR\vlastCommand\x12\x1f\n" +
	"\vlast_output\x18\x04 \x01(\tR\n" +
	"lastOutput\x12$\n" +
	"\x0elast_exit_code\x18\x05 \x01(\x05R\flastExitCode\x12!\n" +
	"\fproject_name\x18\x06 \x01(\tR\vprojectName\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x96\x01\n" +
	"\x11SessionCheckpoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x121\n" +
	"\x05state\x18\x03 \x01(\v2\x1b.sentinel.v1.SessionContextR\x05state\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\x81\x01\n" +
	"\fSessionEvent\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x05R\bsequence2\x8d\x05\n" +
	"\x0eSessionService\x12O\n" +
	"\x06Create\x12!.sentinel.v1.CreateSessionRequest\x1a\".sentinel.v1.CreateSessionResponse\x12O\n" +
	"\x06Resume\x12!.sentinel.v1.ResumeSessionRequest\x1a\".sentinel.v1.ResumeSessionResponse\x12L\n" +
	"\x05Pause\x12 .sentinel.v1.PauseSessionRequest\x1a!.sentinel.v1.PauseSessionResponse\x12O\n" +
	"\x06Status\x12!.sentinel.v1.SessionStatusRequest\x1a\".sentinel.v1.SessionStatusResponse\x12K\n" +
	"\x04List\x12 .sentinel.v1.ListSessionsRequest\x1a!.sentinel.v1.ListSessionsResponse\x12R\n" +
	"\aDestroy\x12\".sentinel.v1.DestroySessionRequest\x1a#.sentinel.v1.DestroySessionResponse\x12M\n" +
	"\n" +
	"Checkpoint\x12\x1e.sentinel.v1.CheckpointRequest\x1a\x1f.sentinel.v1.CheckpointResponse\x12J\n" +
	"\tHeartbeat\x12\x1d.sentinel.v1.HeartbeatRequest\x1a\x1e.sentinel.v1.HeartbeatResponseB0Z.github.com/inovacc/sentinel/internal/api/v1;v1b\x06proto3"

var (
	file_proto_v1_session_proto_rawDescOnce sync.Once
	file_proto_v1_session_proto_rawDescData []byte
)

func file_proto_v1_session_proto_rawDescGZIP() []byte {
	file_proto_v1_session_proto_rawDescOnce.Do(func() {
		file_proto_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_session_proto_rawDesc), len(file_proto_v1_session_proto_rawDesc)))
	})
	return file_proto_v1_session_proto_rawDescData
}

var file_proto_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_v1_session_proto_goTypes = []any{
	(*CreateSessionRequest)(nil),   // 0: sentinel.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil),  // 1: sentinel.v1.CreateSessionResponse
	(*ResumeSessionRequest)(nil),   // 2: sentinel.v1.ResumeSessionRequest
	(*ResumeSessionResponse)(nil),  // 3: sentinel.v1.ResumeSessionResponse
	(*PauseSessionRequest)(nil),    // 4: sentinel.v1.PauseSessionRequest
	(*PauseSessionResponse)(nil),   // 5: sentinel.v1.PauseSessionResponse
	(*SessionStatusRequest)(nil),   // 6: sentinel.v1.SessionStatusRequest
	(*SessionStatusResponse)(nil),  // 7: sentinel.v1.SessionStatusResponse
	(*ListSessionsRequest)(nil),    // 8: sentinel.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),   // 9: sentinel.v1.ListSessionsResponse
	(*SessionSummary)(nil),         // 10: sentinel.v1.SessionSummary
	(*DestroySessionRequest)(nil),  // 11: sentinel.v1.DestroySessionRequest
	(*DestroySessionResponse)(nil), // 12: sentinel.v1.DestroySessionResponse
	(*CheckpointRequest)(nil),      // 13: sentinel.v1.CheckpointRequest
	(*CheckpointResponse)(nil),     // 14: sentinel.v1.CheckpointResponse
	(*HeartbeatRequest)(nil),       // 15: sentinel.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 16: sentinel.v1.HeartbeatResponse
	(*SessionContext)(nil),         // 17: sentinel.v1.SessionContext
	(*SessionCheckpoint)(nil),      // 18: sentinel.v1.SessionCheckpoint
	(*SessionEvent)(nil),           // 19: sentinel.v1.SessionEvent
	nil,                            // 20: sentinel.v1.CreateSessionRequest.EnvEntry
	nil,                            // 21: sentinel.v1.SessionContext.EnvEntry
}
var file_proto_v1_session_proto_depIdxs = []int32{
	20, // 0: sentinel.v1.CreateSessionRequest.env:type_name -> sentinel.v1.CreateSessionRequest.EnvEntry
	17, // 1: sentinel.v1.ResumeSessionResponse.context:type_name -> sentinel.v1.SessionContext
	18, // 2: sentinel.v1.ResumeSessionResponse.last_checkpoint:type_name -> sentinel.v1.SessionCheckpoint
	19, // 3: sentinel.v1.ResumeSessionResponse.recent_events:type_name -> sentinel.v1.SessionEvent
	17, // 4: sentinel.v1.SessionStatusResponse.context:type_name -> sentinel.v1.SessionContext
	10, // 5: sentinel.v1.ListSessionsResponse.sessions:type_name -> sentinel.v1.SessionSummary
	21, // 6: sentinel.v1.SessionContext.env:type_name -> sentinel.v1.SessionContext.EnvEntry
	17, // 7: sentinel.v1.SessionCheckpoint.state:type_name -> sentinel.v1.SessionContext
	0,  // 8: sentinel.v1.SessionService.Create:input_type -> sentinel.v1.CreateSessionRequest
	2,  // 9: sentinel.v1.SessionService.Resume:input_type -> sentinel.v1.ResumeSessionRequest
	4,  // 10: sentinel.v1.SessionService.Pause:input_type -> sentinel.v1.PauseSessionRequest
	6,  // 11: sentinel.v1.SessionService.Status:input_type -> sentinel.v1.SessionStatusRequest
	8,  // 12: sentinel.v1.SessionService.List:input_type -> sentinel.v1.ListSessionsRequest
	11, // 13: sentinel.v1.SessionService.Destroy:input_type -> sentinel.v1.DestroySessionRequest
	13, // 14: sentinel.v1.SessionService.Checkpoint:input_type -> sentinel.v1.CheckpointRequest
	15, // 15: sentinel.v1.SessionService.Heartbeat:input_type -> sentinel.v1.HeartbeatRequest
	1,  // 16: sentinel.v1.SessionService.Create:output_type -> sentinel.v1.CreateSessionResponse
	3,  // 17: sentinel.v1.SessionService.Resume:output_type -> sentinel.v1.ResumeSessionResponse
	5,  // 18: sentinel.v1.SessionService.Pause:output_type -> sentinel.v1.PauseSessionResponse
	7,  // 19: sentinel.v1.SessionService.Status:output_type -> sentinel.v1.SessionStatusResponse
	9,  // 20: sentinel.v1.SessionService.List:output_type -> sentinel.v1.ListSessionsResponse
	12, // 21: sentinel.v1.SessionService.Destroy:output_type -> sentinel.v1.DestroySessionResponse
	14, // 22: sentinel.v1.SessionService.Checkpoint:output_type -> sentinel.v1.CheckpointResponse
	16, // 23: sentinel.v1.SessionService.Heartbeat:output_type -> sentinel.v1.HeartbeatResponse
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_v1_session_proto_init() }
func file_proto_v1_session_proto_init() {
	if File_proto_v1_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_session_proto_rawDesc), len(file_proto_v1_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_session_proto_goTypes,
		DependencyIndexes: file_proto_v1_session_proto_depIdxs,
		MessageInfos:      file_proto_v1_session_proto_msgTypes,
	}.Build()
	File_proto_v1_session_proto = out.File
	file_proto_v1_session_proto_goTypes = nil
	file_proto_v1_session_proto_depIdxs = nil
}
