// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/v1/worker.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerService_Spawn_FullMethodName   = "/sentinel.v1.WorkerService/Spawn"
	WorkerService_List_FullMethodName    = "/sentinel.v1.WorkerService/List"
	WorkerService_Get_FullMethodName     = "/sentinel.v1.WorkerService/Get"
	WorkerService_Kill_FullMethodName    = "/sentinel.v1.WorkerService/Kill"
	WorkerService_KillAll_FullMethodName = "/sentinel.v1.WorkerService/KillAll"
	WorkerService_Wait_FullMethodName    = "/sentinel.v1.WorkerService/Wait"
)

// WorkerServiceClient is the client API for WorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkerService manages parallel task workers on remote machines.
type WorkerServiceClient interface {
	// Spawn a new worker process.
	Spawn(ctx context.Context, in *SpawnWorkerRequest, opts ...grpc.CallOption) (*SpawnWorkerResponse, error)
	// List all workers with optional status filter.
	List(ctx context.Context, in *ListWorkersRequest, opts ...grpc.CallOption) (*ListWorkersResponse, error)
	// Get details for a specific worker.
	Get(ctx context.Context, in *GetWorkerRequest, opts ...grpc.CallOption) (*WorkerInfo, error)
	// Kill a running worker.
	Kill(ctx context.Context, in *KillWorkerRequest, opts ...grpc.CallOption) (*KillWorkerResponse, error)
	// Kill all running workers.
	KillAll(ctx context.Context, in *KillAllWorkersRequest, opts ...grpc.CallOption) (*KillAllWorkersResponse, error)
	// Wait for a worker to complete.
	Wait(ctx context.Context, in *WaitWorkerRequest, opts ...grpc.CallOption) (*WorkerInfo, error)
}

type workerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerServiceClient(cc grpc.ClientConnInterface) WorkerServiceClient {
	return &workerServiceClient{cc}
}

func (c *workerServiceClient) Spawn(ctx context.Context, in *SpawnWorkerRequest, opts ...grpc.CallOption) (*SpawnWorkerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpawnWorkerResponse)
	err := c.cc.Invoke(ctx, WorkerService_Spawn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) List(ctx context.Context, in *ListWorkersRequest, opts ...grpc.CallOption) (*ListWorkersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkersResponse)
	err := c.cc.Invoke(ctx, WorkerService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) Get(ctx context.Context, in *GetWorkerRequest, opts ...grpc.CallOption) (*WorkerInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerInfo)
	err := c.cc.Invoke(ctx, WorkerService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) Kill(ctx context.Context, in *KillWorkerRequest, opts ...grpc.CallOption) (*KillWorkerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KillWorkerResponse)
	err := c.cc.Invoke(ctx, WorkerService_Kill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) KillAll(ctx context.Context, in *KillAllWorkersRequest, opts ...grpc.CallOption) (*KillAllWorkersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KillAllWorkersResponse)
	err := c.cc.Invoke(ctx, WorkerService_KillAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) Wait(ctx context.Context, in *WaitWorkerRequest, opts ...grpc.CallOption) (*WorkerInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerInfo)
	err := c.cc.Invoke(ctx, WorkerService_Wait_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServiceServer is the server API for WorkerService service.
// All implementations must embed UnimplementedWorkerServiceServer
// for forward compatibility.
//
// WorkerService manages parallel task workers on remote machines.
type WorkerServiceServer interface {
	// Spawn a new worker process.
	Spawn(context.Context, *SpawnWorkerRequest) (*SpawnWorkerResponse, error)
	// List all workers with optional status filter.
	List(context.Context, *ListWorkersRequest) (*ListWorkersResponse, error)
	// Get details for a specific worker.
	Get(context.Context, *GetWorkerRequest) (*WorkerInfo, error)
	// Kill a running worker.
	Kill(context.Context, *KillWorkerRequest) (*KillWorkerResponse, error)
	// Kill all running workers.
	KillAll(context.Context, *KillAllWorkersRequest) (*KillAllWorkersResponse, error)
	// Wait for a worker to complete.
	Wait(context.Context, *WaitWorkerRequest) (*WorkerInfo, error)
	mustEmbedUnimplementedWorkerServiceServer()
}

// UnimplementedWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerServiceServer struct{}

func (UnimplementedWorkerServiceServer) Spawn(context.Context, *SpawnWorkerRequest) (*SpawnWorkerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Spawn not implemented")
}
func (UnimplementedWorkerServiceServer) List(context.Context, *ListWorkersRequest) (*ListWorkersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedWorkerServiceServer) Get(context.Context, *GetWorkerRequest) (*WorkerInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedWorkerServiceServer) Kill(context.Context, *KillWorkerRequest) (*KillWorkerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Kill not implemented")
}
func (UnimplementedWorkerServiceServer) KillAll(context.Context, *KillAllWorkersRequest) (*KillAllWorkersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KillAll not implemented")
}
func (UnimplementedWorkerServiceServer) Wait(context.Context, *WaitWorkerRequest) (*WorkerInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Wait not implemented")
}
func (UnimplementedWorkerServiceServer) mustEmbedUnimplementedWorkerServiceServer() {}
func (UnimplementedWorkerServiceServer) testEmbeddedByValue()                       {}

// UnsafeWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServiceServer will
// result in compilation errors.
type UnsafeWorkerServiceServer interface {
	mustEmbedUnimplementedWorkerServiceServer()
}

func RegisterWorkerServiceServer(s grpc.ServiceRegistrar, srv WorkerServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerService_ServiceDesc, srv)
}

func _WorkerService_Spawn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpawnWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).Spawn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_Spawn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).Spawn(ctx, req.(*SpawnWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).List(ctx, req.(*ListWorkersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).Get(ctx, req.(*GetWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_Kill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).Kill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_Kill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).Kill(ctx, req.(*KillWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_KillAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillAllWorkersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).KillAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_KillAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).KillAll(ctx, req.(*KillAllWorkersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_Wait_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).Wait(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_Wait_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).Wait(ctx, req.(*WaitWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerService_ServiceDesc is the grpc.ServiceDesc for WorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sentinel.v1.WorkerService",
	HandlerType: (*WorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Spawn",
			Handler:    _WorkerService_Spawn_Handler,
		},
		{
			MethodName: "List",
			Handler:    _WorkerService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _WorkerService_Get_Handler,
		},
		{
			MethodName: "Kill",
			Handler:    _WorkerService_Kill_Handler,
		},
		{
			MethodName: "KillAll",
			Handler:    _WorkerService_KillAll_Handler,
		},
		{
			MethodName: "Wait",
			Handler:    _WorkerService_Wait_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/worker.proto",
}
