// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/v1/worker.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpawnWorkerRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Command        string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args           []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	WorkingDir     string                 `protobuf:"bytes,3,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	Env            map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SessionId      string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSeconds int32                  `protobuf:"varint,7,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SpawnWorkerRequest) Reset() {
	*x = SpawnWorkerRequest{}
	mi := &file_proto_v1_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnWorkerRequest) ProtoMessage() {}

func (x *SpawnWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnWorkerRequest.ProtoReflect.Descriptor instead.
func (*SpawnWorkerRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_worker_proto_rawDescGZIP(), []int{0}
}

func (x *SpawnWorkerRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *SpawnWorkerRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *SpawnWorkerRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *SpawnWorkerRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *SpawnWorkerRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SpawnWorkerRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SpawnWorkerRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type SpawnWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpawnWorkerResponse) Reset() {
	*x = SpawnWorkerResponse{}
	mi := &file_proto_v1_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnWorkerResponse) ProtoMessage() {}

func (x *SpawnWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnWorkerResponse.ProtoReflect.Descriptor instead.
func (*SpawnWorkerResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_worker_proto_rawDescGZIP(), []int{1}
}

func (x *SpawnWorkerResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *SpawnWorkerResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type ListWorkersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusFilter  string                 `protobuf:"bytes,1,opt,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkersRequest) Reset() {
	*x = ListWorkersRequest{}
	mi := &file_proto_v1_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkersRequest) ProtoMessage() {}

func (x *ListWorkersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkersRequest.ProtoReflect.Descriptor instead.
func (*ListWorkersRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_worker_proto_rawDescGZIP(), []int{2}
}

func (x *ListWorkersRequest) GetStatusFilter() string {
	if x != nil {
		return x.StatusFilter
	}
	return ""
}

type ListWorkersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workers       []*WorkerInfo          `protobuf:"bytes,1,rep,name=workers,proto3" json:"workers,omitempty"`
	ActiveCount   int32                  `protobuf:"varint,2,opt,name=active_count,json=activeCount,proto3" json:"active_count,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkersResponse) Reset() {
	*x = ListWorkersResponse{}
	mi := &file_proto_v1_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkersResponse) ProtoMessage() {}

func (x *ListWorkersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkersResponse.ProtoReflect.Descriptor instead.
func (*ListWorkersResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_worker_proto_rawDescGZIP(), []int{3}
}

func (x *ListWorkersResponse) GetWorkers() []*WorkerInfo {
	if x != nil {
		return x.Workers
	}
	return nil
}

func (x *ListWorkersResponse) GetActiveCount() int32 {
	if x != nil {
		return x.ActiveCount
	}
	return 0
}

func (x *ListWorkersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkerRequest) Reset() {
	*x = GetWorkerRequest{}
	mi := &file_proto_v1_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkerRequest) ProtoMessage() {}

func (x *GetWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkerRequest.ProtoReflect.Descriptor instead.
func (*GetWorkerRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_worker_proto_rawDescGZIP(), []int{4}
}

func (x *GetWorkerRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type KillWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillWorkerRequest) Reset() {
	*x = KillWorkerRequest{}
	mi := &file_proto_v1_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillWorkerRequest) ProtoMessage() {}

func (x *KillWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillWorkerRequest.ProtoReflect.Descriptor instead.
func (*KillWorkerRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_worker_proto_rawDescGZIP(), []int{5}
}

func (x *KillWorkerRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type KillWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Killed        bool                   `protobuf:"varint,1,opt,name=killed,proto3" json:"killed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillWorkerResponse) Reset() {
	*x = KillWorkerResponse{}
	mi := &file_proto_v1_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillWorkerResponse) ProtoMessage() {}

func (x *KillWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillWorkerResponse.ProtoReflect.Descriptor instead.
func (*KillWorkerResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_worker_proto_rawDescGZIP(), []int{6}
}

func (x *KillWorkerResponse) GetKilled() bool {
	if x != nil {
		return x.Killed
	}
	return false
}

type KillAllWorkersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillAllWorkersRequest) Reset() {
	*x = KillAllWorkersRequest{}
	mi := &file_proto_v1_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillAllWorkersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillAllWorkersRequest) ProtoMessage() {}

func (x *KillAllWorkersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillAllWorkersRequest.ProtoReflect.Descriptor instead.
func (*KillAllWorkersRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_worker_proto_rawDescGZIP(), []int{7}
}

type KillAllWorkersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KilledCount   int32                  `protobuf:"varint,1,opt,name=killed_count,json=killedCount,proto3" json:"killed_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillAllWorkersResponse) Reset() {
	*x = KillAllWorkersResponse{}
	mi := &file_proto_v1_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillAllWorkersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillAllWorkersResponse) ProtoMessage() {}

func (x *KillAllWorkersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillAllWorkersResponse.ProtoReflect.Descriptor instead.
func (*KillAllWorkersResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_worker_proto_rawDescGZIP(), []int{8}
}

func (x *KillAllWorkersResponse) GetKilledCount() int32 {
	if x != nil {
		return x.KilledCount
	}
	return 0
}

type WaitWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitWorkerRequest) Reset() {
	*x = WaitWorkerRequest{}
	mi := &file_proto_v1_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitWorkerRequest) ProtoMessage() {}

func (x *WaitWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitWorkerRequest.ProtoReflect.Descriptor instead.
func (*WaitWorkerRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_worker_proto_rawDescGZIP(), []int{9}
}

func (x *WaitWorkerRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type WorkerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Pid           int32                  `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt     int64                  `protobuf:"varint,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    int64                  `protobuf:"varint,8,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	Stdout        string                 `protobuf:"bytes,9,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,10,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32                  `protobuf:"varint,11,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	SessionId     string                 `protobuf:"bytes,12,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,13,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DurationMs    int64                  `protobuf:"varint,14,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerInfo) Reset() {
	*x = WorkerInfo{}
	mi := &file_proto_v1_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerInfo) ProtoMessage() {}

func (x *WorkerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerInfo.ProtoReflect.Descriptor instead.
func (*WorkerInfo) Descriptor() ([]byte, []int) {
	return file_proto_v1_worker_proto_rawDescGZIP(), []int{10}
}

func (x *WorkerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkerInfo) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *WorkerInfo) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *WorkerInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *WorkerInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkerInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *WorkerInfo) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *WorkerInfo) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

func (x *WorkerInfo) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *WorkerInfo) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *WorkerInfo) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *WorkerInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WorkerInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WorkerInfo) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

var File_proto_v1_worker_proto protoreflect.FileDescriptor

const file_proto_v1_worker_proto_rawDesc = "" +
	"\n" +
	"\x15proto/v1/worker.proto\x12\vsentinel.v1\"\xa7\x03\n" +
	"\x12SpawnWorkerRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12\x1f\n" +
	"\vworking_dir\x18\x03 \x01(\tR\n" +
	"workingDir\x12:\n" +
	"\x03env\x18\x04 \x03(\v2(.sentinel.v1.SpawnWorkerRequest.EnvEntryR\x03env\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12I\n" +
	"\bmetadata\x18\x06 \x03(\v2-.sentinel.v1.SpawnWorkerRequest.MetadataEntryR\bmetadata\x12'\n" +
	"\x0ftimeout_seconds\x18\a \x01(\x05R\x0etimeoutSeconds\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\x13SpawnWorkerResponse\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\"9\n" +
	"\x12ListWorkersRequest\x12#\n" +
	"\rstatus_filter\x18\x01 \x01(\tR\fstatusFilter\"\x8c\x01\n" +
	"\x13ListWorkersResponse\x121\n" +
	"\aworkers\x18\x01 \x03(\v2\x17.sentinel.v1.WorkerInfoR\aworkers\x12!\n" +
	"\factive_count\x18\x02 \x01(\x05R\vactiveCount\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"/\n" +
	"\x10GetWorkerRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"0\n" +
	"\x11KillWorkerRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\",\n" +
	"\x12KillWorkerResponse\x12\x16\n" +
	"\x06killed\x18\x01 \x01(\bR\x06killed\"\x17\n" +
	"\x15KillAllWorkersRequest\";\n" +
	"\x16KillAllWorkersResponse\x12!\n" +
	"\fkilled_count\x18\x01 \x01(\x05R\vkilledCount\"0\n" +
	"\x11WaitWorkerRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"\xe0\x03\n" +
	"\n" +
	"WorkerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\x05R\x03pid\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"started_at\x18\a \x01(\x03R\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\b \x01(\x03R\n" +
	"finishedAt\x12\x16\n" +
	"\x06stdout\x18\t \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\n" +
	" \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\v \x01(\x05R\bexitCode\x12\x1d\n" +
	"\n" +
	"session_id\x18\f \x01(\tR\tsessionId\x12A\n" +
	"\bmetadata\x18\r \x03(\v2%.sentinel.v1.WorkerInfo.MetadataEntryR\bmetadata\x12\x1f\n" +
	"\vduration_ms\x18\x0e \x01(\x03R\n" +
	"durationMs\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xc3\x03\n" +
	"\rWorkerService\x12J\n" +
	"\x05Spawn\x12\x1f.sentinel.v1.SpawnWorkerRequest\x1a .sentinel.v1.SpawnWorkerResponse\x12I\n" +
	"\x04List\x12\x1f.sentinel.v1.ListWorkersRequest\x1a .sentinel.v1.ListWorkersResponse\x12=\n" +
	"\x03Get\x12\x1d.sentinel.v1.GetWorkerRequest\x1a\x17.sentinel.v1.WorkerInfo\x12G\n" +
	"\x04Kill\x12\x1e.sentinel.v1.KillWorkerRequest\x1a\x1f.sentinel.v1.KillWorkerResponse\x12R\n" +
	"\aKillAll\x12\".sentinel.v1.KillAllWorkersRequest\x1a#.sentinel.v1.KillAllWorkersResponse\x12?\n" +
	"\x04Wait\x12\x1e.sentinel.v1.WaitWorkerRequest\x1a\x17.sentinel.v1.WorkerInfoB0Z.github.com/inovacc/sentinel/internal/api/v1;v1b\x06proto3"

var (
	file_proto_v1_worker_proto_rawDescOnce sync.Once
	file_proto_v1_worker_proto_rawDescData []byte
)

func file_proto_v1_worker_proto_rawDescGZIP() []byte {
	file_proto_v1_worker_proto_rawDescOnce.Do(func() {
		file_proto_v1_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_worker_proto_rawDesc), len(file_proto_v1_worker_proto_rawDesc)))
	})
	return file_proto_v1_worker_proto_rawDescData
}

var file_proto_v1_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_v1_worker_proto_goTypes = []any{
	(*SpawnWorkerRequest)(nil),     // 0: sentinel.v1.SpawnWorkerRequest
	(*SpawnWorkerResponse)(nil),    // 1: sentinel.v1.SpawnWorkerResponse
	(*ListWorkersRequest)(nil),     // 2: sentinel.v1.ListWorkersRequest
	(*ListWorkersResponse)(nil),    // 3: sentinel.v1.ListWorkersResponse
	(*GetWorkerRequest)(nil),       // 4: sentinel.v1.GetWorkerRequest
	(*KillWorkerRequest)(nil),      // 5: sentinel.v1.KillWorkerRequest
	(*KillWorkerResponse)(nil),     // 6: sentinel.v1.KillWorkerResponse
	(*KillAllWorkersRequest)(nil),  // 7: sentinel.v1.KillAllWorkersRequest
	(*KillAllWorkersResponse)(nil), // 8: sentinel.v1.KillAllWorkersResponse
	(*WaitWorkerRequest)(nil),      // 9: sentinel.v1.WaitWorkerRequest
	(*WorkerInfo)(nil),             // 10: sentinel.v1.WorkerInfo
	nil,                            // 11: sentinel.v1.SpawnWorkerRequest.EnvEntry
	nil,                            // 12: sentinel.v1.SpawnWorkerRequest.MetadataEntry
	nil,                            // 13: sentinel.v1.WorkerInfo.MetadataEntry
}
var file_proto_v1_worker_proto_depIdxs = []int32{
	11, // 0: sentinel.v1.SpawnWorkerRequest.env:type_name -> sentinel.v1.SpawnWorkerRequest.EnvEntry
	12, // 1: sentinel.v1.SpawnWorkerRequest.metadata:type_name -> sentinel.v1.SpawnWorkerRequest.MetadataEntry
	10, // 2: sentinel.v1.ListWorkersResponse.workers:type_name -> sentinel.v1.WorkerInfo
	13, // 3: sentinel.v1.WorkerInfo.metadata:type_name -> sentinel.v1.WorkerInfo.MetadataEntry
	0,  // 4: sentinel.v1.WorkerService.Spawn:input_type -> sentinel.v1.SpawnWorkerRequest
	2,  // 5: sentinel.v1.WorkerService.List:input_type -> sentinel.v1.ListWorkersRequest
	4,  // 6: sentinel.v1.WorkerService.Get:input_type -> sentinel.v1.GetWorkerRequest
	5,  // 7: sentinel.v1.WorkerService.Kill:input_type -> sentinel.v1.KillWorkerRequest
	7,  // 8: sentinel.v1.WorkerService.KillAll:input_type -> sentinel.v1.KillAllWorkersRequest
	9,  // 9: sentinel.v1.WorkerService.Wait:input_type -> sentinel.v1.WaitWorkerRequest
	1,  // 10: sentinel.v1.WorkerService.Spawn:output_type -> sentinel.v1.SpawnWorkerResponse
	3,  // 11: sentinel.v1.WorkerService.List:output_type -> sentinel.v1.ListWorkersResponse
	10, // 12: sentinel.v1.WorkerService.Get:output_type -> sentinel.v1.WorkerInfo
	6,  // 13: sentinel.v1.WorkerService.Kill:output_type -> sentinel.v1.KillWorkerResponse
	8,  // 14: sentinel.v1.WorkerService.KillAll:output_type -> sentinel.v1.KillAllWorkersResponse
	10, // 15: sentinel.v1.WorkerService.Wait:output_type -> sentinel.v1.WorkerInfo
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_v1_worker_proto_init() }
func file_proto_v1_worker_proto_init() {
	if File_proto_v1_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_worker_proto_rawDesc), len(file_proto_v1_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_worker_proto_goTypes,
		DependencyIndexes: file_proto_v1_worker_proto_depIdxs,
		MessageInfos:      file_proto_v1_worker_proto_msgTypes,
	}.Build()
	File_proto_v1_worker_proto = out.File
	file_proto_v1_worker_proto_goTypes = nil
	file_proto_v1_worker_proto_depIdxs = nil
}
